# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NY Times Articles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NY Times Articles

  pod 'SDWebImage', '~> 5.0'
  pod 'ReachabilitySwift'

  target 'NY Times ArticlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
